name: robot
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ampl-asl=1.0.0
  - aom=3.9.1
  - assimp=5.4.2
  - asttokens=3.0.0
  - attr=2.5.1
  - backcall=0.2.0
  - blas=1.0
  - blas-devel=3.9.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.7.14
  - cairo=1.18.0
  - casadi=3.6.5
  - catkin_pkg=1.0.0
  - certifi=2024.8.30
  - cffi=1.17.0
  - charset-normalizer=3.4.0
  - comm=0.2.2
  - console_bridge=1.0.2
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.8.90
  - cuda-runtime=12.1.0
  - cuda-version=12.8
  - dav1d=1.2.1
  - debugpy=1.8.5
  - distro=1.9.0
  - eigen=3.4.0
  - ffmpeg=7.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.12
  - gmp=6.3.0
  - gmpy2=2.1.2
  - graphite2=1.3.14
  - h2=4.1.0
  - harfbuzz=9.0.0
  - hpack=4.0.0
  - hpp-fcl=2.4.5
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.10
  - importlib-metadata=8.5.0
  - intel-openmp=2022.0.1
  - ipopt=3.14.16
  - ipykernel=6.29.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240722.0
  - libass=0.17.3
  - libblas=3.9.0
  - libboost=1.86.0
  - libboost-devel=1.86.0
  - libboost-headers=1.86.0
  - libboost-python=1.86.0
  - libboost-python-devel=1.86.0
  - libcap=2.71
  - libcblas=3.9.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.13.1.3
  - libcurand=10.3.9.90
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.23
  - libdrm=2.4.124
  - libedit=3.1.20191231
  - libegl=1.7.0
  - libexpat=2.7.0
  - libfabric=2.1.0
  - libfabric1=2.1.0
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgcrypt-lib=1.11.0
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgl=1.7.0
  - libglib=2.84.0
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libgpg-error=1.54
  - libhwloc=2.11.2
  - libiconv=1.18
  - libjpeg-turbo=3.0.3
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.6.4
  - libnl=3.11.0
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libopenblas=0.3.21
  - libopenvino=2024.4.0
  - libopenvino-auto-batch-plugin=2024.4.0
  - libopenvino-auto-plugin=2024.4.0
  - libopenvino-hetero-plugin=2024.4.0
  - libopenvino-intel-cpu-plugin=2024.4.0
  - libopenvino-intel-gpu-plugin=2024.4.0
  - libopenvino-intel-npu-plugin=2024.4.0
  - libopenvino-ir-frontend=2024.4.0
  - libopenvino-onnx-frontend=2024.4.0
  - libopenvino-paddle-frontend=2024.4.0
  - libopenvino-pytorch-frontend=2024.4.0
  - libopenvino-tensorflow-frontend=2024.4.0
  - libopenvino-tensorflow-lite-frontend=2024.4.0
  - libopus=1.3.1
  - libosqp=0.6.3
  - libpciaccess=0.18
  - libpng=1.6.47
  - libprotobuf=5.28.2
  - libqdldl=0.1.7
  - librsvg=2.58.4
  - libscotch=7.0.4
  - libsodium=1.0.18
  - libspral=2024.05.08
  - libsqlite=3.45.2
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=257.3
  - libtiff=4.7.0
  - libudev1=257.4
  - libuuid=2.38.1
  - libva=2.22.0
  - libvpx=1.14.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - lz4-c=1.10.0
  - matplotlib-inline=0.1.7
  - metis=5.1.0
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpi=1.0.1
  - mpi4py=4.0.0
  - mpich=4.3.0
  - mpmath=1.3.0
  - mumps-include=5.7.3
  - mumps-seq=5.7.3
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - numpy=1.24.4
  - ocl-icd=2.3.2
  - octomap=1.9.8
  - openblas=0.3.4
  - openh264=2.4.1
  - openjpeg=2.5.3
  - openssl=3.5.1
  - packaging=24.2
  - pango=1.54.0
  - parso=0.8.4
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pinocchio=3.2.0
  - pip=24.2
  - pixman=0.44.2
  - platformdirs=4.3.6
  - pooch=1.8.2
  - prompt_toolkit=3.0.48
  - proxsuite=0.6.7
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pugixml=1.14
  - pure_eval=0.2.3
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.8.18
  - python-dateutil=2.9.0post0
  - python_abi=3.8
  - pytorch=2.3.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - qhull=2020.2
  - qhull-static=2020.2
  - rdma-core=56.0
  - readline=8.2
  - requests=2.32.3
  - rospkg=1.5.1
  - scipy=1.10.1
  - setuptools=75.1.0
  - simde=0.8.2
  - snappy=1.2.1
  - sqlite=3.45.2
  - stack_data=0.6.2
  - svt-av1=2.2.1
  - sympy=1.13.3
  - tbb=2022.0.0
  - tinyxml2=10.0.0
  - tk=8.6.13
  - torchtriton=2.3.1
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - ucx=1.18.0
  - urdfdom=4.0.1
  - urdfdom_headers=1.1.2
  - wayland=1.23.1
  - wayland-protocols=1.42
  - wcwidth=0.2.13
  - wheel=0.44.0
  - x264=1!164.3095
  - x265=3.5
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrender=0.9.12
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - addict==2.4.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiohttp-retry==2.8.3
      - aioice==0.9.0
      - aiortc==1.9.0
      - aiosignal==1.3.1
      - aiosqlite==0.20.0
      - alabaster==0.7.13
      - annotated-types==0.7.0
      - anthropic==0.34.2
      - antlr4-python3-runtime==4.9.3
      - anyio==4.5.2
      - anytree==2.12.1
      - apscheduler==3.11.0
      - arm-pytorch-utilities==0.4.3
      - astroid==3.2.4
      - async-timeout==5.0.1
      - asyncua==1.1.5
      - attrs==25.1.0
      - autoapi==2.0.1
      - av==12.3.0
      - babel==2.17.0
      - backoff==2.2.1
      - backports-zoneinfo==0.2.1
      - beautifulsoup4==4.14.2
      - bidict==0.23.1
      - blinker==1.8.2
      - blosc==1.11.1
      - boto3==1.35.60
      - botocore==1.35.99
      - cachetools==5.5.2
      - chardet==5.2.0
      - chime==0.7.0
      - chumpy==0.70
      - click==8.1.8
      - clip==1.0
      - cloudpickle==3.1.1
      - cmeel==0.57.1
      - cmeel-assimp==5.4.3.1
      - cmeel-boost==1.87.0.1
      - cmeel-console-bridge==1.0.2.2
      - cmeel-octomap==1.10.0
      - cmeel-qhull==8.0.2.1
      - cmeel-tinyxml2==10.0.0
      - cmeel-urdfdom==4.0.1
      - cmeel-zlib==1.3.1
      - coal-library==3.0.1
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - colorlog==6.9.0
      - commonmark==0.9.1
      - configargparse==1.7
      - contourpy==1.1.1
      - cryptography==45.0.4
      - cycler==0.12.1
      - cython==3.0.12
      - dash==2.18.2
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - dataclasses-json==0.6.7
      - decorator==4.4.2
      - defusedxml==0.7.1
      - dex-retargeting==0.5.0
      - dnspython==2.6.1
      - docker==7.1.0
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - docutils==0.20.1
      - eigenpy==3.10.3
      - einops==0.8.1
      - embreex==2.17.7.post6
      - eval-type-backport==0.2.2
      - evdev==1.9.1
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - farama-notifications==0.0.4
      - fastapi==0.110.3
      - fastjsonschema==2.21.1
      - filelock==3.16.1
      - flask==3.0.3
      - flask-socketio==5.5.1
      - flatbuffers==25.2.10
      - fonttools==4.56.0
      - freetype-py==2.5.1
      - frozenlist==1.5.0
      - fsspec==2025.2.0
      - ftfy==6.2.3
      - furo==2024.8.6
      - future==1.0.0
      - fvcore==0.1.5.post20221221
      - git-filter-repo==2.47.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - glfw==2.9.0
      - google-auth==2.38.0
      - google-auth-oauthlib==1.0.0
      - google-crc32c==1.5.0
      - grpcio==1.70.0
      - gym==0.23.1
      - gym-notices==0.1.0
      - gymnasium==0.29.1
      - gymnasium-robotics==1.2.4
      - h11==0.16.0
      - h5py==3.11.0
      - hf-xet==1.1.3
      - httpcore==1.0.9
      - httpx==0.27.2
      - huggingface-hub==0.33.0
      - humanfriendly==10.0
      - hydra==2.5
      - hydra-core==1.3.2
      - ifaddr==0.2.0
      - ikpy==3.4.2
      - imageio==2.35.1
      - imageio-ffmpeg==0.5.1
      - imagesize==1.4.1
      - importlib-resources==6.4.5
      - inference==0.37.1
      - iniconfig==2.1.0
      - iopath==0.1.10
      - ipdb==0.13.13
      - ipython==8.12.3
      - ipywidgets==8.1.5
      - iso8601==2.1.0
      - itsdangerous==2.2.0
      - jax==0.4.13
      - jaxlib==0.4.13
      - jedi==0.19.2
      - jinja2==3.1.5
      - jiter==0.9.1
      - jmespath==1.0.1
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyterlab-widgets==3.0.13
      - keyboard==0.13.5
      - kiwisolver==1.4.7
      - kornia==0.7.3
      - kornia-rs==0.1.9
      - lazy-loader==0.4
      - lightning-utilities==0.11.9
      - loguru==0.7.3
      - lxml==5.3.1
      - manifold3d==3.1.1
      - manotorch==0.0.2
      - mapbox-earcut==1.0.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - marshmallow==3.22.0
      - matplotlib==3.7.5
      - mdurl==0.1.2
      - mediapipe==0.10.11
      - ml-dtypes==0.2.0
      - modbus==3.2
      - moviepy==1.0.3
      - msgspec==0.18.6
      - mujoco==2.3.7
      - multidict==6.1.0
      - mypy-extensions==1.1.0
      - narwhals==1.29.0
      - nbformat==5.10.4
      - netifaces==0.11.0
      - networkx==2.2
      - ninja==1.11.1.4
      - nlopt==2.7.1
      - nodeenv==1.9.1
      - numpy-quaternion==2023.0.4
      - nvdiffrast==0.3.3
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-curobo==0.0.0
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.575.51
      - nvidia-nccl-cu11==2.20.5
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.8.61
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - onnxruntime==1.19.2
      - open3d==0.19.0
      - openai==1.86.0
      - opencv-contrib-python==4.10.0.84
      - opencv-python==4.11.0.86
      - opt-einsum==3.4.0
      - paho-mqtt==1.6.1
      - pandas==2.0.3
      - pathtools==0.1.2
      - pettingzoo==1.24.3
      - pin==3.4.0
      - pkgutil-resolve-name==1.3.10
      - plotly==6.0.0
      - pluggy==1.5.0
      - plyfile==1.0.3
      - portalocker==3.0.0
      - proglog==0.1.12
      - prometheus-client==0.21.1
      - prometheus-fastapi-instrumentator==6.0.0
      - promise==2.3
      - prompt-toolkit==3.0.50
      - propcache==0.2.0
      - protobuf==3.20.3
      - psutil==5.9.8
      - py-cpuinfo==9.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybase64==1.0.2
      - pybind11==3.0.1
      - pycollada==0.6
      - pycolmap==3.11.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydantic-settings==2.8.1
      - pydot==2.0.0
      - pyee==13.0.0
      - pygame==2.1.0
      - pyglet==1.5.27
      - pygments==2.19.1
      - pyjwt==2.9.0
      - pyliblzfse==0.4.1
      - pylibsrtp==0.10.0
      - pylogix==1.0.5
      - pymodbus==3.6.9
      - pynput==1.8.0
      - pyopengl==3.1.0
      - pyopenssl==25.1.0
      - pyparsing==3.1.4
      - pyquaternion==0.9.9
      - pyrealsense2==2.54.2.5684
      - pyrender==0.1.45
      - pysdf==0.1.9
      - pyserial==3.5
      - pysoem==1.1.13
      - pytest==8.3.5
      - python-dotenv==1.0.1
      - python-engineio==4.12.3
      - python-socketio==5.15.0
      - python-xlib==0.33
      - pytorch-kinematics==0.7.5
      - pytorch-lightning==2.4.0
      - pytorch-seed==0.2.0
      - pytransform3d==3.14.0
      - pytz==2025.1
      - pyusb==1.2.1
      - pyvirtualdisplay==3.0
      - pyvisa==1.14.1
      - pyvisa-py==0.7.2
      - pywavelets==1.4.1
      - pyzmq==26.2.1
      - redis==5.0.8
      - referencing==0.35.1
      - regex==2024.11.6
      - requests-file==2.1.0
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - retrying==1.3.4
      - rich==14.0.0
      - rl-games==1.6.1
      - rpds-py==0.20.1
      - rsa==4.9
      - rtree==1.3.0
      - s3transfer==0.10.4
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - seaborn==0.13.2
      - segment-anything==1.0
      - sentry-sdk==2.42.1
      - setproctitle==1.3.7
      - setuptools-scm==9.2.0
      - shapely==2.0.7
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - shtab==1.7.1
      - simple-websocket==1.1.0
      - six==1.17.0
      - slack-sdk==3.33.5
      - smmap==5.0.2
      - smplx==0.1.28
      - sniffio==1.3.1
      - snowballstemmer==3.0.1
      - sortedcontainers==2.4.0
      - sounddevice==0.5.2
      - soupsieve==2.7
      - sphinx==7.1.2
      - sphinx-autoapi==3.5.0
      - sphinx-basic-ng==1.0.0b2
      - sphinxcontrib-applehelp==1.0.4
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - spinnaker-python==3.2.0.57
      - stack-data==0.6.3
      - starlette==0.37.2
      - stdlib-list==0.10.0
      - structlog==24.4.0
      - supervision==0.25.1
      - svg-path==6.3
      - tabulate==0.9.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - tldextract==5.1.2
      - tokenizers==0.20.3
      - tomli==2.2.1
      - torch==2.4.1+cu118
      - torchaudio==2.4.1+cu118
      - torchmetrics==1.5.2
      - torchvision==0.19.1
      - tqdm==4.67.1
      - transforms3d==0.4.2
      - trimesh==3.23.5
      - triton==3.0.0
      - twilio==9.3.8
      - typeguard==4.4.0
      - typer==0.12.5
      - typing-inspect==0.9.0
      - tyro==0.9.16
      - tzdata==2025.1
      - tzlocal==5.2
      - ultralytics==8.3.154
      - ultralytics-thop==2.0.14
      - urdf-parser-py==0.0.4
      - urdfpy==0.0.22
      - urllib3==1.26.20
      - usb==0.0.83.dev0
      - usd-core==25.11
      - viser==1.0.4
      - wandb==0.12.21
      - warp-lang==0.10.1
      - websockets==13.1
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.13
      - wsproto==1.2.0
      - xacro==1.13.3
      - xatlas==0.0.10
      - xxhash==3.5.0
      - yacs==0.1.8
      - yarl==1.15.2
      - yourdfpy==0.0.57
      - zipp==3.20.2
      - zmq==0.0.0
      - zxing-cpp==2.2.0
