defaults:
  - _self_
  - network
  - robot: allegro
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

hydra:  
  output_subdir: null  
  run:  
    dir: .

data_dir: "/home/temp_id/isaac/data"