import os
import shutil
import argparse

from paradex.utils.file_io import find_latest_directory
from paradex.calibration.utils import handeye_calib_path

def delete_generated_files(name):
    """Delete all files generated by calculate.py"""
    root_dir = os.path.join(handeye_calib_path, name)

    if not os.path.exists(root_dir):
        print(f"Directory {root_dir} does not exist.")
        return

    index_list = sorted(os.listdir(root_dir))

    # Files to delete in each index folder
    files_to_delete = [
        "charuco_3d_ids.npy",
        "charuco_3d_corners.npy",
        "eef_fk.npy",
        "C2R.npy",
    ]

    # Folders to delete in each index folder
    folders_to_delete = [
        "undistort",
        "detection",
        "debug",
    ]

    for index in index_list:
        index_path = os.path.join(root_dir, index)

        if not os.path.isdir(index_path):
            continue

        print(f"Processing index {index}...")

        # Delete files
        for filename in files_to_delete:
            file_path = os.path.join(index_path, filename)
            if os.path.exists(file_path):
                os.remove(file_path)
                print(f"  Deleted: {filename}")

        # Delete folders
        for folder in folders_to_delete:
            folder_path = os.path.join(index_path, folder)
            if os.path.exists(folder_path):
                shutil.rmtree(folder_path)
                print(f"  Deleted folder: {folder}/")

    print("Done.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--name", type=str, default=None, help="Name of the calibration directory.")
    args = parser.parse_args()

    if args.name is None:
        args.name = find_latest_directory(handeye_calib_path)

    print(f"Deleting generated files from: {args.name}")
    delete_generated_files(args.name)
