robot_cfg:
  kinematics:
    use_usd_kinematics: false
    usd_path: ''
    usd_robot_root: ''
    isaac_usd_path: ''
    usd_flip_joints: {}
    usd_flip_joint_limits: []
    urdf_path: xarm_allegro_v5.urdf
    asset_root_path: rsc/robot
    external_asset_path: rsc/robot
    base_link: link_base
    ee_link: wrist
    link_names:
      - link1
      - link2
      - link3
      - link4
      - link5
      - link6
      - wrist
      - palm_link
      - link_0_0
      - link_1_0
      - link_2_0
      - link_3_0
      - link_3_0_tip
      - link_4_0
      - link_5_0
      - link_6_0
      - link_7_0
      - link_7_0_tip
      - link_8_0
      - link_9_0
      - link_10_0
      - link_11_0
      - link_11_0_tip
      - link_12_0
      - link_13_0
      - link_14_0
      - link_15_0
      - link_15_0_tip
    collision_link_names:
      - link_base
      - link1
      - link2
      - link3
      - link4
      - link5
      - link6
      - palm_link
      - link_1_0
      - link_2_0
      - link_3_0_tip
      - link_5_0
      - link_6_0
      - link_7_0_tip
      - link_9_0
      - link_10_0
      - link_11_0_tip
      - link_12_0
      - link_14_0
      - link_15_0
      - link_15_0_tip
    collision_spheres: rsc/curobo/content/configs/robot/spheres/xarm_allegro_v5.yml
    collision_sphere_buffer: 0.0
    self_collision_ignore:
      link_base: [link1]
      link1: [link2]
      link2: [link3]
      link3: [link4]
      link4: [link5]
      link5:
        - link6
        - palm_link
        - link_1_0
        - link_2_0
        - link_3_0_tip
        - link_5_0
        - link_6_0
        - link_7_0_tip
        - link_9_0
        - link_10_0
        - link_11_0_tip
        - link_12_0
        - link_14_0
        - link_15_0
        - link_15_0_tip
      link6:
        - palm_link
        - link_1_0
        - link_2_0
        - link_3_0_tip
        - link_5_0
        - link_6_0
        - link_7_0_tip
        - link_9_0
        - link_10_0
        - link_11_0_tip
        - link_12_0
        - link_14_0
        - link_15_0
        - link_15_0_tip
      palm_link:
        - link_1_0
        - link_5_0
        - link_9_0
        - link_12_0
        - link_14_0
      link_1_0: [link_2_0]
      link_2_0: [link_3_0_tip]
      link_5_0: [link_6_0]
      link_6_0: [link_7_0_tip]
      link_9_0: [link_10_0]
      link_10_0: [link_11_0_tip]
      link_12_0: [link_14_0]
      link_14_0: [link_15_0]
      link_15_0: [link_15_0_tip]
    self_collision_buffer:
      link_base: 0
      link1: 0
      link2: 0
      link3: 0
      link4: 0
      link5: 0
      link6: 0
      palm_link: 0.0
      link_1_0: 0.0
      link_2_0: 0.0
      link_3_0_tip: 0.0
      link_5_0: 0.0
      link_6_0: 0.0
      link_7_0_tip: 0.0
      link_9_0: 0.0
      link_10_0: 0.0
      link_11_0_tip: 0.0
      link_12_0: 0.0
      link_14_0: 0.0
      link_15_0: 0.0
      link_15_0_tip: 0.0
    use_global_cumul: true
    mesh_link_names:
      - link_base
      - link1
      - link2
      - link3
      - link4
      - link5
      - link6
      - palm_link
      - link_0_0
      - link_1_0
      - link_2_0
      - link_3_0
      - link_3_0_tip
      - link_4_0
      - link_5_0
      - link_6_0
      - link_7_0
      - link_7_0_tip
      - link_8_0
      - link_9_0
      - link_10_0
      - link_11_0
      - link_11_0_tip
      - link_12_0
      - link_13_0
      - link_14_0
      - link_15_0
      - link_15_0_tip
    lock_joints:
      joint_0_0: 0.0
      joint_1_0: 0.0
      joint_2_0: 0.0
      joint_3_0: 0.0
      joint_4_0: 0.0
      joint_5_0: 0.0
      joint_6_0: 0.0
      joint_7_0: 0.0
      joint_8_0: 0.0
      joint_9_0: 0.0
      joint_10_0: 0.0
      joint_11_0: 0.0
      joint_12_0: 0.0
      joint_13_0: 0.0
      joint_14_0: 0.0
      joint_15_0: 0.0
    cspace:
      joint_names:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6
        - joint_0_0
        - joint_1_0
        - joint_2_0
        - joint_3_0
        - joint_4_0
        - joint_5_0
        - joint_6_0
        - joint_7_0
        - joint_8_0
        - joint_9_0
        - joint_10_0
        - joint_11_0
        - joint_12_0
        - joint_13_0
        - joint_14_0
        - joint_15_0
      retract_config:
        - -1.26711
        - -0.20246
        - -1.13621
        - 2.33176
        - 0.32289
        - 2.36492
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
      cspace_distance_weight: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
      null_space_weight:     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
      max_jerk: 500.0
      max_acceleration: 15.0
