robot_name: allegro_xarm

# Detection from the oculus
receiver:
  -
    _target_: dex_robot.teleop.components.receiver.OculusVRHandReceiver
    host: ${host_address}
    oculus_port: ${oculus_reciever_port}
    button_port: ${resolution_button_port}
    teleop_reset_port: ${teleop_reset_port}
    

# Transforming the keypoints from the oculus
transformer:
  - 
    _target_: dex_robot.teleop.components.keypoint_transformer.WristFrameHandPose

retargeter:
  - 
    _target_: dex_robot.teleop.components.retargeter.AllegroRetargeter
    finger_configs:
      freeze_index: false
      freeze_middle: false
      freeze_ring: false
      freeze_thumb: false
      no_index: false
      no_middle: false 
      no_ring: false
      no_thumb: false
      three_dim: true
    init_robot_hand_joint_angle_path : ${data_dir}/home_pose/allegro_hand_joint_angle.npy
    init_robot_eef_frame_path : ${data_dir}/home_pose/allegro_eef_frame.npy
    moving_average_limit : 5
